# Generated by Django 2.2.6 on 2019-12-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressupdate',
            old_name='email',
            new_name='request_email',
        ),
    ]
