# Generated by Django 2.2.6 on 2019-12-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191211_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressUpdate',
        ),
    ]
