# Generated by Django 2.2.6 on 2019-11-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-username',), 'verbose_name_plural': 'Administrators'},
        ),
    ]
