# Generated by Django 2.2.6 on 2019-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191119_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Medical Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Secretary', 'Secretary'), ('Department of Health Rep', 'Health Officer')], default=False, max_length=30),
        ),
    ]
