# Generated by Django 2.2.6 on 2019-11-09 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191105_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid username', message='Username must be alphanumeric or contain numbers', regex='^[a-zA-Z0-9.+-]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('position', models.CharField(choices=[('Medical Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Secretary', 'Secretary'), ('Department of Health Rep', 'Health Officer')], max_length=70, verbose_name='Level of Access')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Authorised Users',
                'ordering': ('-username',),
            },
        ),
    ]
