# Generated by Django 2.2.6 on 2019-11-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='unique_id',
        ),
    ]
