# Generated by Django 2.2.6 on 2019-11-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Mr', 'MR.'), ('Mrs', 'MRS.'), ('Ms', 'MS.'), ('Prof', 'PROF.'), ('Dr', 'DR.'), ('Rev', 'REV.')], max_length=6),
        ),
    ]
