# Generated by Django 2.2.6 on 2019-12-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0002_auto_20191206_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blood_type', to='HealthNet.BloodGroup'),
        ),
    ]
