# Generated by Django 2.2.6 on 2019-12-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0002_auto_20191205_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital', to='HealthNet.HospitalsAndClinics'),
        ),
    ]
