# Generated by Django 2.2.6 on 2019-12-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('id',), 'verbose_name_plural': 'Staff'},
        ),
    ]
