# Generated by Django 2.2.6 on 2019-11-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0002_auto_20191106_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('identification_id', models.CharField(max_length=60, unique=True)),
                ('qualification', models.CharField(max_length=60)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='HealthNet.HospitalStaff')),
            ],
            options={
                'verbose_name_plural': 'Authorised Personnel',
            },
        ),
    ]
