# Generated by Django 2.2.6 on 2019-11-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0003_hospitalstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=12)),
                ('date_of_birth', models.DateField()),
                ('physical_address', models.CharField(max_length=255)),
                ('chronic_disease', models.BooleanField()),
                ('national_id', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('blood_type', models.CharField(choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type')], max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('marital_status', models.CharField(choices=[('N/A', 'Not Applicable'), ('ENGAGED', 'Engaged'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('MARRIED', 'Married')], max_length=20)),
                ('medical_aid_group', models.CharField(choices=[('Not Applicable', 'N/A'), ('masca', 'MASCA'), ('nust medical aid', 'NUST Medical AID'), ('humana', 'Humana'), ('premier', 'Premier Services'), ('psmas', 'PSMAS'), ('emergency24', 'Emergency 24'), ('EA', 'Emblem Healthcare'), ('zimaid', 'ZimAid'), ('KP', 'Kaiser Permanente'), ('WP', 'Wellpoint')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Records',
            },
        ),
    ]
