# Generated by Django 2.2.6 on 2019-12-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0003_auto_20191206_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
