# Generated by Django 2.2.6 on 2019-11-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0004_medicalrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('question', 'Question'), ('suggestion', 'Suggestion'), ('other', 'Other')], max_length=30)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_mass',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_temperature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description_of_the_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
