# Generated by Django 2.2.6 on 2019-12-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0004_auto_20191206_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
