# Generated by Django 2.2.6 on 2019-12-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0005_auto_20191206_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_mass',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
