# Generated by Django 2.2.6 on 2019-12-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0006_auto_20191214_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalsandclinics',
            name='name',
            field=models.CharField(choices=[('Mpilo Central Hospital', 'Mpilo Hospital'), ('Mater Dei Hospital', 'Mater Dei'), ('United Bulawayo Hospitals', 'UBH'), ('CIMAS', 'Cimas'), ('Corporate 24', 'Corporate 24'), ('Emergency 24', 'Emergency 24'), ('Parirenyatwa General Hospital', 'Parirenyatwa Hospital'), ('Lancet House', 'Lancet House'), ('Mutare General Hospital', 'Mutare General'), ('Kwekwe General Hospital', 'Kwekwe General'), ('Avenues Clinic', 'Avenues')], max_length=60),
        ),
    ]
