# Generated by Django 2.2.6 on 2019-12-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0007_auto_20191214_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='consulted_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='HealthNet.Doctor'),
        ),
    ]
