# Generated by Django 2.2.6 on 2019-11-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0007_patient_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(height_field='80', null=True, upload_to='images/', width_field='80'),
        ),
    ]
