# Generated by Django 2.2.6 on 2019-12-14 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0008_auto_20191214_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood', to='HealthNet.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='HealthNet.HospitalsAndClinics'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_aid_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_aid_user', to='HealthNet.MedicalAidScheme'),
        ),
    ]
