# Generated by Django 2.2.6 on 2019-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0009_auto_20191111_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='identification_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
