# Generated by Django 2.2.6 on 2019-12-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0009_auto_20191214_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_type', to='HealthNet.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='HealthNet.Doctor'),
        ),
        migrations.AlterField(
            model_name='hospitalsandclinics',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='HealthNet.HospitalsAndClinics'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='blood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blood', to='HealthNet.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='medical_aid_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_aid_used', to='HealthNet.MedicalAidScheme'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='HealthNet.Staff'),
        ),
    ]
