# Generated by Django 2.2.6 on 2020-02-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0010_auto_20191214_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('id',), 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id'], 'verbose_name_plural': 'Patients'},
        ),
    ]
