# Generated by Django 2.2.6 on 2019-11-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0011_auto_20191111_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('identification_id',), 'verbose_name_plural': 'Doctors'},
        ),
    ]
