# Generated by Django 2.2.6 on 2019-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0012_auto_20191112_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='medical_aid_group',
            field=models.CharField(choices=[('Not Applicable', 'N/A'), ('Masca', 'MASCA'), ('NUST Medical Aid', 'NUST Medical AID'), ('Humana', 'Humana'), ('Premier', 'Premier Services'), ('PSMAS', 'PSMAS'), ('Emergency24', 'Emergency 24'), ('EA', 'Emblem Healthcare'), ('ZimAid', 'ZimAid'), ('KP', 'Kaiser Permanente'), ('WP', 'Wellpoint')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_mass',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='employment_status',
            field=models.CharField(choices=[('Not Applicable', 'NOT APPLICABLE'), ('Employed', 'EMPLOYED'), ('Unemployed', 'UNEMPLOYED'), ('Contract Employee', 'CONTRACT EMPLOYEE'), ('Student', 'STUDENT'), ('Retired', 'RETIRED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_aid_group',
            field=models.CharField(choices=[('Not Applicable', 'N/A'), ('Masca', 'MASCA'), ('NUST Medical Aid', 'NUST Medical AID'), ('Humana', 'Humana'), ('Premier', 'Premier Services'), ('PSMAS', 'PSMAS'), ('Emergency24', 'Emergency 24'), ('EA', 'Emblem Healthcare'), ('ZimAid', 'ZimAid'), ('KP', 'Kaiser Permanente'), ('WP', 'Wellpoint')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mr', 'MR.'), ('Mrs', 'MRS.'), ('Ms', 'MS.'), ('Prof', 'PROF.'), ('Dr', 'DR.'), ('Rev', 'REV.')], max_length=10),
        ),
    ]
