# Generated by Django 2.2.6 on 2020-02-28 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0012_auto_20200228_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='marital_status',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('ENGAGED', 'Engaged'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, default='Maize', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='2009-2-15'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, default='simoegaranganga@iCloud.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Lisa', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='4934 Prinsloo Road, Burnside', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Garanganga', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('ENGAGED', 'Engaged'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='75-8888277U64', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+263 73 989 8332', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
