# Generated by Django 2.2.6 on 2020-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0013_auto_20200228_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Email',
            new_name='staff_email',
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, default='dog', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='2000-11-15'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, default='samkelenyakasikana@hotmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Elijah', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='53069 Mbare Road, Hillside', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Nkiwane', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='43-426480Y94', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+263 77 561 3762', max_length=30, unique=True),
        ),
    ]
