# Generated by Django 2.2.6 on 2019-11-15 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0013_auto_20191112_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=6)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=7)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('identification_id', models.CharField(default='', max_length=30, unique=True)),
                ('position', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='HealthNet.Staff')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ('identification_id',),
            },
        ),
    ]
