# Generated by Django 2.2.6 on 2019-11-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0014_auto_20191115_0408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalStaff',
        ),
    ]
