# Generated by Django 2.2.6 on 2020-03-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0015_auto_20200317_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalaidscheme',
            name='name',
            field=models.CharField(choices=[('None', 'None'), ('Masca', 'MASCA'), ('CIMAS', 'CIMAS'), ('Liberty Health Cover', 'Liberty Blue'), ('Alliance Health', 'Alliance Health'), ('PSMAS', 'PSMAS'), ('Health International', 'Health International'), ('Fidelity', 'Fidelity Life Insurance'), ('Minerva', 'Minerva')], max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='Wheat', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='1956-11-17'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(default='susanmanyuchi@aol.com', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Queen', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='4538 Ellison Road, Trenance', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Stinta', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='51-2806046Z09', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+263 73 791 7230', max_length=30, unique=True),
        ),
    ]
