# Generated by Django 2.2.6 on 2019-11-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0015_delete_hospitalstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
