# Generated by Django 2.2.6 on 2019-11-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0016_staff_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
