# Generated by Django 2.2.6 on 2020-03-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0016_auto_20200317_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Email',
            new_name='doctor_email',
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='FruitGarlic', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='2003-1-23'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(default='tendainkiwane@protonmail.com', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Samkele', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='73 Mbare Road, Mt Pleasant', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Mupfumira', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='64-752529Z90', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+263 73 873 8337', max_length=30, unique=True),
        ),
    ]
