# Generated by Django 2.2.6 on 2020-03-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0018_auto_20200317_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='assigned_patient',
        ),
        migrations.AddField(
            model_name='doctor',
            name='assigned_patient',
            field=models.ManyToManyField(related_name='patients', to='HealthNet.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='cosmetics', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='1999-10-16'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(default='bridgetchafa@yahoo.com', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Anopa', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='82 Jason Moyo Ave, Cowdray Park', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='82-236159L92', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+263 71 081 6408', max_length=30, unique=True),
        ),
    ]
