# Generated by Django 2.2.6 on 2020-03-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0020_auto_20200317_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='assigned_patient',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='parent',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='HealthNet.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='1930-11-29'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(default='brightonsibindi@iCloud.com', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='William', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='621 State House Ave, Sunninghill', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Olsen', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='71-665651L39', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+263 71 391 2021', max_length=30, unique=True),
        ),
    ]
