# Generated by Django 2.2.6 on 2020-06-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0024_auto_20200424_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='medicalaidscheme',
            name='name',
            field=models.CharField(choices=[('Masca', 'MASCA'), ('CIMAS', 'CIMAS'), ('Liberty Health Cover', 'Liberty Blue'), ('Alliance Health', 'Alliance Health'), ('PSMAS', 'PSMAS'), ('Health International', 'Health International'), ('Fidelity', 'Fidelity Life Insurance'), ('Minerva', 'Minerva')], max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='Maize', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='1916-6-19'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(default='mukudzeimbele@yahoo.co.uk', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Cherrie', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='17 Brentwood Road, Burnside', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Mapfumo', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='26-588304E99', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+263 71 224 9746', max_length=30, unique=True),
        ),
    ]
