# Generated by Django 2.2.6 on 2019-10-26 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('home_address', models.CharField(default='', max_length=255)),
                ('national_id', models.CharField(default='', max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(default='example@gmail.com', max_length=254)),
                ('purpose_of_visit', models.CharField(max_length=255)),
                ('description_of_the_condition', models.TextField()),
                ('prescription', models.CharField(max_length=255)),
                ('current_temperature', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=255)),
                ('current_medication', models.CharField(max_length=255)),
                ('body_mass', models.CharField(max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('consulted_doctor', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=20)),
                ('medical_aid_group', models.CharField(max_length=255)),
                ('date_of_visit', models.DateField(default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
