# Generated by Django 2.2.6 on 2019-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('first_name', models.CharField(default=False, max_length=255)),
                ('last_name', models.CharField(default=False, max_length=255)),
                ('date_of_birth', models.DateField(default=False)),
                ('home_addr', models.CharField(default=False, max_length=255)),
                ('national_id', models.CharField(default=False, max_length=30)),
                ('phone_number', models.CharField(default=False, max_length=30)),
                ('email_addr', models.EmailField(default=False, max_length=254)),
                ('purpose_of_visit', models.CharField(default=False, max_length=255)),
                ('prescription', models.CharField(default=False, max_length=255)),
                ('curr_temp', models.CharField(default=False, max_length=255)),
                ('blood_group', models.CharField(default=False, max_length=255)),
                ('current_med', models.CharField(default=False, max_length=255)),
                ('body_mass', models.CharField(default=False, max_length=255)),
                ('allergies', models.CharField(default=False, max_length=255)),
                ('consulted_dr', models.CharField(default=False, max_length=255)),
                ('employment_status', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=20)),
                ('medical_aid_group', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'ordering': ('-last_name',),
            },
        ),
    ]
