# Generated by Django 2.2.6 on 2019-10-20 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 5, 41, 11, 257242)),
        ),
    ]
