# Generated by Django 2.2.6 on 2019-10-21 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_date_of_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='home_addr',
        ),
        migrations.AddField(
            model_name='patient',
            name='description_of_condition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'o+'), ('O-', 'o-'), ('AB', 'ab'), ('A', 'a'), ('B', 'b')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_mass',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='consulted_dr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='curr_temp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_med',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 2, 41, 8, 60618)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prefix',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='purpose_of_visit',
            field=models.CharField(max_length=255),
        ),
    ]
