# Generated by Django 2.2.6 on 2019-11-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='Dr', max_length=6)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=60)),
                ('specialty', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
